# Numpy

In [1]:
import numpy as np

In [4]:
myarr = np.array([2,5,7,9], np.int8)     #this will provide memory to that list
myarr

array([2, 5, 7, 9], dtype=int8)

In [6]:
myarr = np.array([[2,5,7,9]], np.int8)    
myarr[0,1]

5

In [8]:
myarr = np.array([[2,5,7,9]], np.int8)   
myarr.dtype

dtype('int8')

In [9]:
myarr = np.array([[2,5,7,9]], np.int8)   
myarr.shape

(1, 4)

In [13]:
myarr = np.array([[2,5,7,9]], np.int8)   
myarr[0,1] = 10
myarr

array([[ 2, 10,  7,  9]], dtype=int8)

## Array creation : Conversion from other python structures

In [15]:
listarray = np.array([[1,2,3], [4,5,6], [7,8,9]])
listarray


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
listarray = np.array([[1,2,3], [4,5,6], [7,8,9]])
listarray.dtype


dtype('int32')

In [17]:
listarray = np.array([[1,2,3], [4,5,6], [7,8,9]])
listarray.size

9

In [19]:
np.array({32, 45, 89})

array({32, 89, 45}, dtype=object)

In [21]:
zeros = np.zeros((2,6))
zeros

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [22]:
rng = np.arange(10)
rng

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
lspace = np.linspace(1,3,6)          #it will provide 6 equal spaces from 1-3 
lspace

array([1. , 1.4, 1.8, 2.2, 2.6, 3. ])

In [25]:
emp = np.empty((4,6))                 # it will provide random numbers of array of [4,6]
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        6.23047842e-307, 2.22526399e-307, 6.23053614e-307],
       [7.56592338e-307, 1.60216183e-306, 7.56602523e-307,
        3.56043054e-307, 1.37961641e-306, 2.22518251e-306],
       [1.33511969e-306, 6.23037657e-307, 6.23053954e-307,
        9.34609790e-307, 8.45593934e-307, 9.34600963e-307],
       [1.86921143e-306, 6.23061763e-307, 6.23053954e-307,
        7.56602523e-307, 8.90095411e-307, 2.56765117e-312]])

In [26]:
emp_like = np.empty_like(lspace)
emp_like

array([1. , 1.4, 1.8, 2.2, 2.6, 3. ])

In [27]:
ide = np.identity(10)          # it provides identity matrix of 10
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [28]:
ide.shape

(10, 10)

In [29]:
arr = np.arange(50)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [30]:
arr.reshape(5,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [31]:
arr = arr.ravel()       #it will take back to original shape

In [32]:
arr.shape

(50,)

## Numpy axis

In [34]:
x = [[1,2,3], [4,5,6], [7,8,9]]
ar = np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
ar.sum(axis=0)       #it will give sum of vertical column

array([12, 15, 18])

In [37]:
ar.sum(axis=1)       #it will give sum of horizontal row

array([ 6, 15, 24])

In [38]:
ar.T                  #this gives transpose of given array

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [39]:
ar.flat
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [40]:
ar.ndim           # this will give dimension of matrix

2

In [41]:
ar.size

9

In [42]:
ar.nbytes

36

In [44]:
# 1D array
one = np.array([1,4,7,8])
one.argmax()                       #this method provides index of max value

3

In [46]:
one.argmin()                        #this method provides index of max value

0

In [48]:
one.argsort()                        #this method provides sorted array index values

array([0, 1, 2, 3], dtype=int64)

In [49]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
ar.argmin()

0

In [51]:
ar.argmax()

8

In [52]:
ar.argmax(axis=0)

array([2, 2, 2], dtype=int64)

In [53]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
ar.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [55]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
ar1 = np.array([[1,4,6], [3,7,0], [8,3,2]])
ar1

array([[1, 4, 6],
       [3, 7, 0],
       [8, 3, 2]])

In [58]:
ar + ar1

array([[ 2,  6,  9],
       [ 7, 12,  6],
       [15, 11, 11]])

In [59]:
ar * ar1

array([[ 1,  8, 18],
       [12, 35,  0],
       [56, 24, 18]])

In [60]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [61]:
ar.sum()

45

In [62]:
ar.max()

9

In [63]:
ar.min()

1

In [64]:
type(np.where(ar > 5))

tuple

In [65]:
np.where(ar > 5)

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [67]:
np.count_nonzero(ar)

9

In [68]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [71]:
import sys
py_ar = [0,6,2,4]
np_ar = np.array(py_ar)
sys.getsizeof(1) + len(py_ar)            #it gives answer in bytes

32

In [72]:
np_ar.itemsize * np_ar.size                   #it gives answer in bytes

16

In [ ]:
np_ar.tolist()